services:
  codelab-db:
    image: postgres
    container_name: codelab-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codelab-db
    ports:
      - "5432:5432"
    volumes:
      - codelab_db_data:/var/lib/postgresql/data

volumes:
  codelab_db_data:
